USING_DATASET = "TRAIN_V8_100p_5i"
# USING_DATASET = "TRAIN_V4_100p_25i"

DATASET_FOLDER = "./dataset/" + USING_DATASET
EMBDDINGS_FOLDER_EXT = "./embddings/" + USING_DATASET + "_ext.npz"
EMBDDINGS_FOLDER_EMB = "./embddings/" + USING_DATASET + "_emb.npz"